Repository w3b3d3v/web3task-contracts, pull requests merged in 2023-10, with the labels that each got.

#21 Feat: Implementation of scripts to interact with the contract
  scripts/deploy.ts
  scripts/emergengyWithdraw.ts
  scripts/fundingContract.ts
  scripts/getMulticallTask.ts
Labels: implementation

#32 feat: add unitary tests for everything
  contracts/Web3Task.sol
  contracts/interfaces/IWeb3Task.sol
  test/Web3Task.test.ts
Labels: enhancement, good first issue, bull

#36 fix: make better name and description when mocking tasks
  scripts/createTasks.ts
Labels: enhancement

#37 feat: already voted expansion with quorum, better score set
  contracts/Web3Task.sol
  contracts/interfaces/IWeb3Task.sol
  scripts/createTasks.ts
  scripts/setRole.ts
Labels: enhancement, help wanted

#38 fix: time issues, getTasks when task completed, reviews of tasks and quorum rule
  contracts/Web3Task.sol
  contracts/interfaces/IWeb3Task.sol
  scripts/createTasks.ts
  scripts/setRole.ts
  scripts/utils.ts
Labels: enhancement, help wanted

#42 fix: completed tasks cannot be canceled
  contracts/Web3Task.sol
Labels: enhancement
